name = "horariostec-api-v2"
main = "src/index.ts"
compatibility_date = "2026-07-28"

[[d1_databases]]
binding = "DB"
database_name = "horariostec"
database_id = "fa38b7f7-fe69-4dae-a1e2-995abf512948"
migrations_dir = "../api/migrations"

[vars]
ALLOWED_ORIGINS = "https://horariostec.pages.dev,https://horariostec.com"

[dev]
ip = "0.0.0.0"
